# Generated by Django 3.2.8 on 2021-10-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cchoice',
            new_name='CCchoice',
        ),
        migrations.RenameModel(
            old_name='Cquestion',
            new_name='CCquestion',
        ),
    ]
