# Generated by Django 3.2.8 on 2021-10-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0002_auto_20211021_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCchoice',
            new_name='CCchoiceA',
        ),
        migrations.RenameModel(
            old_name='CCquestion',
            new_name='CCquestionA',
        ),
    ]
