# Generated by Django 3.2.8 on 2021-10-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0003_auto_20211021_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCchoiceA',
            new_name='Cchoise',
        ),
        migrations.RenameModel(
            old_name='CCquestionA',
            new_name='Cquestion',
        ),
    ]
