# Generated by Django 3.2.8 on 2021-10-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0004_auto_20211022_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cchoise',
            new_name='Cchoise1',
        ),
        migrations.RenameModel(
            old_name='Cquestion',
            new_name='Cquestion1',
        ),
    ]
